export { WorkoutsTable, type WorkoutsTableProps } from './WorkoutsTable'
export { WorkoutStatusBadge } from './WorkoutStatusBadge'
export { WorkoutDetailView, type WorkoutDetailViewProps } from './WorkoutDetailView'
export { WorkoutExerciseCard, SetSummaryTile } from './WorkoutExerciseCard'
export { ProgressFilters, type ProgressFiltersProps } from './ProgressFilters'
export { ProgressStats, type ProgressStatsProps } from './ProgressStats'
export { ProgressChartCard, type ProgressChartCardProps } from './ProgressChartCard'
export { ClientWorkoutsPanel, type ClientWorkoutsPanelProps } from './ClientWorkoutsPanel'
export { ClientWorkoutDetailPanel, type ClientWorkoutDetailPanelProps } from './ClientWorkoutDetailPanel'
export { ClientProgressPanel, type ClientProgressPanelProps } from './ClientProgressPanel'
